#!/usr/bin/env bash

# Exit immediately if a command exits with a non-zero status
set -euo pipefail

# Get the directory of this script
DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TARGET_DIR="$HOME/.config"

echo "========================================="
echo " Setting up Dotfiles from: $DOTFILES_DIR"
echo "========================================="

# Define the files/directories to symlink
# Format: "source_path_relative_to_repo:destination_path_relative_to_home"
LINKS=(
    ".config/i3:.config/i3"
    ".config/i3status:.config/i3status"
    ".bashrc:.bashrc"
    ".prettierrc:.prettierrc"
)

for entry in "${LINKS[@]}"; do
    # Split the entry into source and destination
    IFS=":" read -r src_rel dest_rel <<< "$entry"
    
    SRC="$DOTFILES_DIR/$src_rel"
    DEST="$HOME/$dest_rel"
    
    # Skip if the source file/directory does not exist in the repository
    if [ ! -e "$SRC" ]; then
        continue
    fi

    echo "Configuring: ~/$dest_rel"

    # Ensure parent directory of destination exists
    DEST_DIR=$(dirname "$DEST")
    mkdir -p "$DEST_DIR"

    # Clean up any existing file, folder, or symlink at target to avoid conflicts
    rm -rf "$DEST"

    # Create the symlink
    ln -s "$SRC" "$DEST"
    echo "  ✔ Symlink created successfully!"
done

echo "========================================="
echo " Configuring Monitor Layout"
echo "========================================="

# Query connected monitors using xrandr
if command -v xrandr &> /dev/null; then
    # Filter connected monitors (avoiding internal empty lines or active line parts)
    MONITORS=($(xrandr --query | grep " connected" | cut -d" " -f1))
else
    MONITORS=()
fi

if [ ${#MONITORS[@]} -ge 2 ]; then
    echo "Multiple monitors detected: ${MONITORS[*]}"
    echo "Please configure your layout."
    
    # Prompt for top monitor
    echo "Which monitor is on TOP?"
    for i in "${!MONITORS[@]}"; do
        echo "  $((i+1))) ${MONITORS[$i]}"
    done
    read -rp "Enter number (default: 1): " top_idx
    if [[ "$top_idx" =~ ^[0-9]+$ ]] && [ "$top_idx" -ge 1 ] && [ "$top_idx" -le "${#MONITORS[@]}" ]; then
        TOP_MONITOR="${MONITORS[$((top_idx-1))]}"
    else
        TOP_MONITOR="${MONITORS[0]}"
    fi
    
    # Filter remaining for bottom monitor
    REMAINING_MONITORS=()
    for m in "${MONITORS[@]}"; do
        if [ "$m" != "$TOP_MONITOR" ]; then
            REMAINING_MONITORS+=("$m")
        fi
    done
    
    echo "Which monitor is on BOTTOM?"
    for i in "${!REMAINING_MONITORS[@]}"; do
        echo "  $((i+1))) ${REMAINING_MONITORS[$i]}"
    done
    read -rp "Enter number (default: 1): " bottom_idx
    if [[ "$bottom_idx" =~ ^[0-9]+$ ]] && [ "$bottom_idx" -ge 1 ] && [ "$bottom_idx" -le "${#REMAINING_MONITORS[@]}" ]; then
        BOTTOM_MONITOR="${REMAINING_MONITORS[$((bottom_idx-1))]}"
    else
        BOTTOM_MONITOR="${REMAINING_MONITORS[0]}"
    fi
else
    # Fallback to standard names if less than 2 monitors are found or xrandr is missing
    TOP_MONITOR="HDMI-A-0"
    BOTTOM_MONITOR="DisplayPort-0"
    echo "⚠ Less than 2 monitors detected (or xrandr not available)."
    echo "Using default/fallback monitor values: TOP=$TOP_MONITOR, BOTTOM=$BOTTOM_MONITOR"
fi

# Write monitors.conf
MONITORS_CONF="$TARGET_DIR/i3/monitors.conf"
echo "Writing monitor definitions to: $MONITORS_CONF"
cat << EOF > "$MONITORS_CONF"
# Auto-generated by setup.sh. Do not commit.
set \$top_monitor $TOP_MONITOR
set \$bottom_monitor $BOTTOM_MONITOR
EOF

# Verify Python dependency
if ! command -v python3 &>/dev/null; then
    echo "⚠ Warning: python3 is not installed. smart_workspace.py will not work."
elif ! python3 -c "import i3ipc" &>/dev/null; then
    echo "⚠ Warning: python3 library 'i3ipc' is not installed. Please install it with your package manager or 'pip install i3ipc'."
fi

echo "========================================="
echo " Setup complete!"
echo "========================================="
